"""backend/output/pdf_export.py — Generates ReportLab PDFs for stakeholder views."""

import asyncio
import io
from typing import Literal
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
try:
    from backend.models.brd import MergedBRD
except ImportError:
    from models.brd import MergedBRD


class NumberedCanvas(canvas.Canvas):
    """Canvas that captures all page states to write accurate total page counts and footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(HexColor("#64748B"))

        # Running header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(40, 755, "PRISM — Autonomous Multi-Agent Synthesis Specification")
            self.setStrokeColor(HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(40, 750, 572, 750)

        # Running footer (all pages)
        self.setStrokeColor(HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(40, 42, 572, 42)
        self.drawString(40, 30, "CONFIDENTIAL & PROPRIETARY — GENERATED BY PRISM AI SWARM")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(572, 30, page_str)
        self.restoreState()


def _sync_generate_pdf(merged_brd: MergedBRD, view: Literal["investor", "technical", "regulatory"]) -> bytes:
    """CPU-bound ReportLab PDF document builder with professional editorial document styling."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=55,
    )

    styles = getSampleStyleSheet()

    # Color Palette per view
    color_map = {
        "investor": HexColor("#1E3A8A"),  # Deep Navy
        "technical": HexColor("#047857"),  # Forest Emerald
        "regulatory": HexColor("#B45309"),  # Amber
        "deliberation": HexColor("#6D28D9"),  # Violet
        "final": HexColor("#0F172A"),  # Slate / Obsidian
    }
    primary_color = color_map.get(view, HexColor("#0F172A"))

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=primary_color,
        spaceAfter=4,
    )

    meta_label_style = ParagraphStyle(
        "MetaLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=HexColor("#334155"),
    )

    meta_val_style = ParagraphStyle(
        "MetaVal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=HexColor("#0F172A"),
    )

    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=12,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "BodyContent",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=HexColor("#1E293B"),
        spaceAfter=6,
    )

    lineage_style = ParagraphStyle(
        "LineageBadge",
        parent=styles["Italic"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        leading=10,
        textColor=HexColor("#475569"),
        spaceAfter=4,
    )

    story = []

    # Title & Header
    view_title_map = {
        "investor": "Investor & Commercial Evaluation BRD",
        "technical": "Technical Architecture & Systems BRD",
        "regulatory": "Regulatory Compliance & Risk Governance BRD",
        "deliberation": "Swarm Deliberation & Dialectics Report",
        "final": "Complete Master Business Requirements Document",
    }
    doc_title = view_title_map.get(view, "Complete Master Business Requirements Document")
    story.append(Paragraph(f"PRISM — {doc_title}", title_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=primary_color, spaceBefore=4, spaceAfter=8))

    # Document Metadata Table
    score_display = f"{merged_brd.investor_readiness_score}/100" if merged_brd.investor_readiness_score is not None else "Verified"
    view_label = "Complete Master BRD" if view in ("final", "full") else view.capitalize()
    meta_data = [
        [
            Paragraph("<b>Document ID:</b>", meta_label_style),
            Paragraph(f"PRD-{merged_brd.session_id[:8].upper()}", meta_val_style),
            Paragraph("<b>PRISM Score:</b>", meta_label_style),
            Paragraph(score_display, meta_val_style),
        ],
        [
            Paragraph("<b>View Perspective:</b>", meta_label_style),
            Paragraph(view_label, meta_val_style),
            Paragraph("<b>Swarm Consensus:</b>", meta_label_style),
            Paragraph("6 Autonomous Personas", meta_val_style),
        ],
    ]
    meta_table = Table(meta_data, colWidths=[110, 155, 110, 155])
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # Sections Filtered & Prioritized by View
    sections = merged_brd.sections or []
    if view == "investor":
        ordered_sections = sorted(
            sections,
            key=lambda s: 0 if any(k in s.title.lower() for k in ["market", "business", "financial", "pricing", "value", "exec"]) else 1,
        )
    elif view == "technical":
        ordered_sections = sorted(
            sections,
            key=lambda s: 0 if any(k in s.title.lower() for k in ["technical", "system", "architecture", "data", "infrastructure", "functional"]) else 1,
        )
    elif view == "regulatory":
        ordered_sections = sorted(
            sections,
            key=lambda s: 0 if any(k in s.title.lower() for k in ["regulatory", "compliance", "legal", "risk", "security"]) else 1,
        )
    else:
        # Full/Final view preserves natural document section flow
        ordered_sections = sections

    for idx, sec in enumerate(ordered_sections, 1):
        story.append(Paragraph(f"{idx:02d}. {sec.title}", heading_style))
        if sec.lineage:
            cit = f" | Evidence Citation: {sec.lineage.data_citation}" if sec.lineage.data_citation else ""
            agent_str = sec.lineage.source_agent.value.upper() if hasattr(sec.lineage.source_agent, "value") else str(sec.lineage.source_agent).upper()
            lineage_info = f"[Synthesized from: {agent_str} agent | Confidence: {int(sec.lineage.confidence * 100)}%{cit}]"
            story.append(Paragraph(lineage_info, lineage_style))

        # Format paragraphs and list items cleanly
        content_clean = sec.content.replace("[SOURCE:", "(Verified Source:").replace("]", ")")
        story.append(Paragraph(content_clean.replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 4))

    # Assumptions Block
    if merged_brd.assumptions:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Identified Unvalidated Assumptions & Stress Points", heading_style))
        for asm in merged_brd.assumptions:
            ev = f"<br/>&nbsp;&nbsp;<i>Grounding Evidence: {asm.evidence}</i>" if asm.evidence else ""
            text = f"• <b>[{asm.confidence.upper()} RISK]</b> {asm.assumption}{ev}<br/>&nbsp;&nbsp;<b>Mitigation Action:</b> {asm.recommended_action}"
            story.append(Paragraph(text, body_style))

    # Failure Modes Block
    if merged_brd.failure_modes:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Adversarial Risk Register & Failure Simulations", heading_style))
        for fm in merged_brd.failure_modes:
            text = f"• <b>{fm.title} ({fm.probability_pct}% Probability)</b>: {fm.description}<br/>&nbsp;&nbsp;<b>Mitigation:</b> {fm.mitigation}"
            story.append(Paragraph(text, body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


async def generate_pdf(merged_brd: MergedBRD, view: str = "final") -> bytes:
    """Generate stakeholder PDF bytes asynchronously off the main event loop."""
    return await asyncio.to_thread(_sync_generate_pdf, merged_brd, view)
