import { useState, useCallback } from 'react'
import { motion } from 'framer-motion'
import { getBrdSectionVariants } from '../../animations/variants.js'
import { AssumptionFlag } from './AssumptionFlag.jsx'
import { BRDSection } from './BRDSection.jsx'
import './BRDViewer.css'

export default function BRDViewer({ sections, assumptions = [] }) {
  const [copied, setCopied] = useState(false)
  const variants = getBrdSectionVariants()

  const handleCopyMarkdown = useCallback(() => {
    let md = `# Business Requirements Document (BRD)\n*Generated by PRISM Multi-Agent Consensus Swarm*\n\n---\n\n`

    sections.forEach((sec, idx) => {
      md += `## ${idx + 1}. ${sec.title}\n\n`
      md += `${sec.content}\n\n`
      if (sec.lineage) {
        md += `> **Source Agent:** ${sec.lineage.sourceAgent || 'Multi-Agent'} (${sec.lineage.confidence || '90%'})\n`
        if (sec.lineage.dataCitation) {
          md += `> **Evidence Citation:** ${sec.lineage.dataCitation}\n`
        }
        md += `\n`
      }
    })

    if (assumptions.length > 0) {
      md += `\n---\n\n## Key Assumptions & Validation Actions\n\n`
      assumptions.forEach((asm) => {
        md += `- **[${(asm.confidenceLevel || 'MEDIUM').toUpperCase()}]** ${asm.text}\n`
        if (asm.evidence) md += `  - *Evidence:* ${asm.evidence}\n`
        if (asm.recommendedAction) md += `  - *Action:* ${asm.recommendedAction}\n`
      })
    }

    navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }, [sections, assumptions])

  return (
    <div className="brd-viewer" aria-live="polite">
      <div className="flex items-center justify-between pb-3 mb-2 border-b border-border-subtle">
        <div className="font-display font-bold text-xs uppercase tracking-wider text-content-secondary flex items-center gap-2">
          <span>📑</span>
          <span>Synthesized Specification ({sections.length} Sections)</span>
        </div>
        <button
          type="button"
          onClick={handleCopyMarkdown}
          className="font-display text-xs font-semibold px-3 py-1.5 rounded border border-border bg-surface hover:bg-surface-raised transition-colors flex items-center gap-1.5 shadow-xs cursor-pointer"
        >
          {copied ? (
            <>
              <span className="text-success font-bold">✓</span>
              <span className="text-success">Copied to Clipboard!</span>
            </>
          ) : (
            <>
              <span>📋</span>
              <span>Copy as Jira / Markdown</span>
            </>
          )}
        </button>
      </div>
      {sections.map((section, index) => (
        <motion.div
          key={section.title}
          variants={variants}
          custom={index}
          initial="hidden"
          animate="visible"
        >
          <BRDSection
            title={section.title}
            content={section.content}
            lineage={section.lineage}
            dissentingAgents={section.dissentingAgents}
          />
        </motion.div>
      ))}

      {assumptions.length > 0 && (
        <section className="brd-viewer__assumptions" aria-label="Hidden assumptions">
          <h2 className="brd-viewer__assumptions-title">Hidden assumptions</h2>
          {assumptions.map((item) => (
            <AssumptionFlag
              key={item.text}
              text={item.text}
              confidenceLevel={item.confidenceLevel}
              evidence={item.evidence}
              recommendedAction={item.recommendedAction}
            />
          ))}
        </section>
      )}
    </div>
  )
}
