import React, { useState } from 'react';

export function BRDViewer({ brdData }) {
  const [showDiff, setShowDiff] = useState(false);

  if (!brdData) {
    return <div className="p-8 text-center text-slate-500 text-sm">No BRD document loaded.</div>;
  }

  return (
    <div className="bg-slate-900/70 border border-slate-800 rounded-2xl p-6 space-y-6">
      <div className="flex justify-between items-center border-b border-slate-800 pb-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100">{brdData.title || 'Business Requirements Document'}</h2>
          <p className="text-xs text-slate-400 mt-1">Generated by PRISM Multi-Agent Engine</p>
        </div>
        <button
          onClick={() => setShowDiff(!showDiff)}
          className={`text-xs px-3 py-1.5 rounded-lg border font-medium transition-colors ${
            showDiff ? 'bg-amber-500/20 border-amber-500/50 text-amber-300' : 'bg-slate-800 border-slate-700 text-slate-300 hover:bg-slate-700'
          }`}
        >
          {showDiff ? 'Hide Iteration Diff' : 'Show Iteration Diff'}
        </button>
      </div>

      {showDiff && (
        <div className="p-3 bg-amber-950/30 border border-amber-800/40 rounded-xl text-xs text-amber-200">
          Viewing consensus highlights against iteration 1.
        </div>
      )}

      <div className="prose prose-invert max-w-none text-sm text-slate-300">
        <p>{brdData.summary || 'Consensus synthesized across persona models.'}</p>
      </div>
    </div>
  );
}
