"""backend/models/agents.py — Pydantic models for swarm agents and evaluator outputs."""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field


AgentName = Literal["vc", "lean", "cto", "ux", "regulator", "adversarial"]
SectionName = Literal[
    "problem_statement",
    "functional_requirements",
    "technical_requirements",
    "risk_register",
    "timeline_milestones",
]
CriterionName = Literal[
    "feasibility",
    "market_timing",
    "regulatory_safety",
    "user_adoption",
    "competitive_moat",
]


class AgentRawSection(BaseModel):
    """A single BRD section generated by an individual swarm agent."""

    content: str
    key_assumptions: List[str] = Field(default_factory=list)
    perceived_risks: List[str] = Field(default_factory=list)


class AgentOutput(BaseModel):
    """Complete output produced by a single swarm agent."""

    session_id: str
    agent_name: AgentName
    sections: Dict[SectionName, AgentRawSection]
    generated_at: str


class SingleScore(BaseModel):
    """Scoring result for one agent section against one rubric criterion."""

    score_id: str
    session_id: str
    agent_name: AgentName
    section_name: SectionName
    criterion: CriterionName
    score: float = Field(..., ge=0.0, le=100.0)
    citation: Optional[str] = None
    evaluated_at: str


class ScoreMatrix(BaseModel):
    """Aggregated evaluator scores across all agents and criteria."""

    session_id: str
    winning_agent: AgentName
    composite_scores: Dict[AgentName, float]
    scores: List[SingleScore] = Field(default_factory=list)
    evaluated_at: str
